name: lip_reader
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  file_picker: ^6.1.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  provider: ^6.1.1
  video_player: ^2.8.2

dev_dependencies:


  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/
